server:
  port: 13000
spring:
  application:
    name: "gateway"
  cloud:
    gateway:
      routes:
        - id: "consumer"
          uri: lb://consumer
          predicates:
            - Path=/cart/**
      global-cors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            # 允许所有域名跨域
            allowedOrigins: "*"
            # 允许所有方法
            allowedMethods: "*"
            # 允许所有请求头
            allowedHeaders: "*"
            maxAge: 3600
eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://localhost:18000/eureka/"
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        waitDurationInOpenState: 5s
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      fall:
        failureRateThreshold: 30